apiVersion: v1
kind: Pod
metadata:
  name: {{ .Release.Name }}-api
  labels:
    app: {{ .Release.Name }}-task-manager
    service: api
spec:
  containers:
  - name: api
    image: {{ .Values.global.registry }}/task-manager-api:{{ .Values.api.tag }}
    ports:
    - containerPort: 5000
    env:
    - name: REDIS_HOST
      value: "{{ .Release.Name }}-db"
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-api
spec:
  selector:
    app: {{ .Release.Name }}-task-manager
    service: api
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
  type: ClusterIP
