apiVersion: v1
kind: Pod
metadata:
  name: {{ .Release.Name }}-db
  labels:
    app: {{ .Release.Name }}-task-manager
    service: db
spec:
  containers:
  - name: db
    image: redis:8.4.0-alpine
    ports:
    - containerPort: 6379
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-db
spec:
  selector:
    app: {{ .Release.Name }}-task-manager
    service: db
  ports:
    - protocol: TCP
      port: 6379
      targetPort: 6379
  type: ClusterIP
