apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-frontend-cm
data:
  default.conf: |
    server {
        listen 80;
        
        # Kubernetes internal DNS resolver
        resolver 10.96.0.10 valid=5s;

        location / {
            root /usr/share/nginx/html;
            index index.html;
        }

        location /api/python/ {
            rewrite ^/api/python/(.*) /$1 break;
            proxy_pass http://{{ .Release.Name }}-api:5000;
            proxy_method $request_method;
        }

        location /api/go/ {
            rewrite ^/api/go/(.*) /$1 break;
            proxy_pass http://{{ .Release.Name }}-monitor:8080;
        }
    }
