apiVersion: v1
kind: Pod
metadata:
  name: task-manager-db
  labels:
    app: task-manager
    service: db
spec:
  containers:
  - name: db
    image: redis:8.4.0-alpine
    command:
      - redis-server
      - "/redis-config/redis.conf"
    ports:
    - containerPort: 6379
    volumeMounts:
    - mountPath: /redis-config
      name: config
  volumes:
    - name: config
      secret:
        secretName: task-manager-secret
        items:
        - key: srv-password
          path: redis.conf
---
apiVersion: v1
kind: Service
metadata:
  name: db
spec:
  selector:
    service: db
  ports:
    - protocol: TCP
      port: 6379
      targetPort: 6379
  type: ClusterIP
