apiVersion: v1
kind: Pod
metadata:
  name: task-manager-monitor
  labels:
    app: task-manager
    service: monitor
spec:
  containers:
  - name: monitor
    image: 192.168.56.12:5000/task-manager-monitor:latest
    ports:
    - containerPort: 8080
    env:
    - name: REDIS_HOST
      value: "db"
---
apiVersion: v1
kind: Service
metadata:
  name: monitor
spec:
  selector:
    service: monitor
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP
