cli_password: ENC[AES256_GCM,data:zowRT12Fstc9IykBzw==,iv:GlIlLFTgF1fdXO/r/0CUIB+gmCmx7krCsNKjNb9bMec=,tag:xdWFi0Mg9I2ns2UO4QJlew==,type:str]
srv_password: ENC[AES256_GCM,data:e6lM4QRQ4MJWTBbvxja2NO5MfKlSIUPSVQ==,iv:kpmA/U4uXs48ldKdAD3jRJsA+Lvyqb8qa/LfP2lhzNo=,tag:si/bGXcWofg+soks67AoWg==,type:str]
sops:
    age:
        - recipient: age1725pgstdn9rrct8j6uq0sw6rj85ju79tew65lp8dy389s4yfaydq92q8l4
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0VE1sdzltUm95SGFqeHhB
            MHNFc29nVGxxcXViVmlJSFRjei9HaURYZWwwCisyWEs0VGdCcTlvenNxM09XOTVM
            SG1QQkNON3NETGQ0bEl0UDZzVnFWb1kKLS0tIG9POG4rTG9TTVNQRmZpRXBWQk1h
            RnhTTTQ4MGN5TGNTRStlTUUwMHNtQUEK+349CyWj9t75+ncGUp08ztCsApBgIrlw
            8ve5nSG1v8D4ZIj2h+in4ewm5P1SKodxD0KaZNAs6bMhZZqcM3yHhQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-22T12:59:03Z"
    mac: ENC[AES256_GCM,data:Fj/57GF3JPsQG8R8KdPEBmA0MXVKk9gCgLeoI2lau+C/WVzRpNH9CF9bmVDmlIoGlKwc3rr8/KqVVHunScMaxN/aN8pjgKXFIBvYFu5eH791YPL1cuCTVf/EfTh9N6n04PA+uoeze8LomZufyypBAp1GN3J7Zw7mdjXGSCVHnIY=,iv:LWxsg5HMQrtKOseg1hoykZogg3zwQd9whPam/DUZ30I=,tag:XX26RLUcULcFB10pQZH1Hg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
